### ISSUE TITLE
Decoding non J1939 CAN using a DBC

### ISSUE THREAD

**Issue by sshenker85** [CSS-Electronics/can_decoder#5]
It seems the function "df_decoder.decode_frame(df_raw_1)" only supports decoding J1939 CAN with a J1939 dbc. Is it possible to get this function to support decoding standard CAN with a standard DBC (regular single frame CAN messages - no Transport protocol)?

Thanks for you help,

**Comment by MatinF** [comment]
Yes, the DBC decoding works for any CAN DBC, not specific to the J1939 case. But if your DBC states that it's a J1939 DBC in the ProtocolType field it will be interpreted as a J1939 DBC by the API. To solve this, you can set the value of the ProtocolType field to "". Let me know if this clarifies.

**Comment by sshenker85** [comment]
Thanks for your quick response, This solved my issue!
