### ISSUE TITLE
How to decode data in a specific format

### ISSUE THREAD

**Issue by smpshehan** [CSS-Electronics/can_decoder#7]
Hi,
I am using the dbc file from CSS electronics to decode CAN Data.
I have CAN data as following format: 
CF00400#FFFFFFC080FFFFFF

first part is CAN Id (or frame id) : CF00400
second part (CAN data) : FFFFFFC080FFFFFF

How do I decode this CAN data using the can_decoder?
`df_decoder.decode_frame(df_raw, columns_to_drop=["CAN ID", "Raw Value"])`
How do I construct the df_raw based on above CAN data?

**Comment by MatinF** [comment]
Hi there, I suggest seeing our api-examples where you can test this with the J1939 sample data:
api-examples/examples at master · CSS-Electronics/api-examples
